services:
  odoo-service:  # Fixed service name
    image: odoo:18
    container_name: ${PROJECT_NAME}  # Will be replaced by script
    ports:
      - "10031:8069"
      - "10032:8071"
      - "10033:8072"
    volumes:
      - ${PROJECT_NAME}-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
    environment:
      - HOST=shared-postgres
      - USER=odoo
      - PASSWORD=odoo
    command: >
      bash -c "
      if [ ! -f /var/lib/odoo/.initialized ]; then
        odoo -c /etc/odoo/odoo.conf -d ${PROJECT_NAME}_demo -i base --stop-after-init &&
        touch /var/lib/odoo/.initialized;
      fi;
      odoo -c /etc/odoo/odoo.conf"
    networks:
      - shared-postgres-network
    env_file:
      - .env

networks:
  shared-postgres-network:
    external: true

volumes:
  ${PROJECT_NAME}-web-data:
